name: Unit Tests

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

#      - uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: arn:aws:iam::0000000000000:role/****
#          aws-region: ap-northeast-1

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --frozen --extra dev

      - name: Run unit tests
        env:
          ENV: CI
        run: uv run pytest tests/unittests/
